apiVersion: apps/v1
kind: Deployment
metadata:
  name: walrus-application
  namespace: walrus-namespace
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - walrus-application
              topologyKey: kubernetes.io/hostname