apiVersion: apps/v1
kind: Deployment
metadata:
  name: walrus-application
  namespace: walrus-namespace
spec:
  template:
    spec:
      containers:
        - name: walrus-application
          volumeMounts:
            - mountPath: /var/log/nginx
              name: pod-logs-dir
      volumes:
        - hostPath:
            path: /data/api_log/default/walrus-application
            type: ''
          name: pod-logs-dir