apiVersion: apps/v1
kind: Deployment
metadata:
  name: walrus-application
  namespace: walrus-namespace
spec:
  template:
    spec:
      containers:
        - name: walrus-application 
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/prometheus
              port: walrus-port
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/prometheus
              port: walrus-port
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5