apiVersion: apps/v1
kind: Deployment
metadata:
  name: walrus-application
spec:
  template:
    spec:
      initContainers:
        - name: sw-agent-sidecar
          image: >-
            h.walrus.com/etc/skywalking-agent-sidecar:8.4.0
          command:
            - sh
          args:
            - '-c'
            - >-
              mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/*
              /skywalking/agent
          resources: {}
          volumeMounts:
            - name: sw-agent
              mountPath: /skywalking/agent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
       