apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
#- cpu_count.yaml
- podAntiAffinity.yaml
- health.yaml
- resources_quota.yaml
- volumes.yaml
- replicas.yaml
- env.yaml