apiVersion: apps/v1
kind: Deployment
metadata:
  name: walrus-application
spec:
  template:
    spec:
      containers:
        - name: walrus-application
          volumeMounts:
            - mountPath: /log
              name: pod-logs-dir
      volumes:
        - hostPath:
            path: /data/api_log/lamb
            type: ''
          name: pod-logs-dir